-- local catppuccin = require("catppuccin")

-- catppuccin.setup {
--   transparent_background = false,
--   term_colors = false,
--   styles = {
--     comments = "italic",
--     functions = "italic",
--     keywords = "italic",
--     strings = "NONE",
--     variables = "italic",
--   },
--   integrations = {
--     treesitter = true,
--     native_lsp = {
--       enabled = false,
--       virtual_text = {
--         errors = "italic",
--         hints = "italic",
--         warnings = "italic",
--         information = "italic",
--       },
--       underlines = {
--         errors = "underline",
--         hints = "underline",
--         warnings = "underline",
--         information = "underline",
--       },
--     },
--     lsp_trouble = false,
--     cmp = false,
--     lsp_saga = false,
--     gitgutter = false,
--     gitsigns = true,
--     telescope = true,
--     nvimtree = {
--       enabled = true,
--       show_root = true,
--     },
--     which_key = true,
--     indent_blankline = {
--       enabled = true,
--       colored_indent_levels = false,
--     },
--     dashboard = true,
--     neogit = false,
--     vim_sneak = false,
--     fern = false,
--     barbar = true,
--     bufferline = true,
--     markdown = true,
--     lightspeed = false,
--     ts_rainbow = false,
--     hop = false,
--     notify = true,
--     telekasten = false,
--   }
-- }

vim.cmd("colorscheme night-owl")
